### Important Mathematical Function
 ##### Aggregation (Sum,Prod,min,max,mean.std,var,meadian,argmin,argmax)
 ##### Power  (square, sqrt, pow(a,b))
 ##### Rounding (round, ceil, floor, trunc)
 ##### Log & Exponential (log, log10, log2, exp)
 ##### Some Other Function (unique, sort, abs)

In [1]:
import numpy as np

In [2]:
#mathematical fnx => #aggregration

arr=np.array([1,2,3,4,5])

print(np.sum(arr))      # Sum of all elements => 1+2+3+4+5
print(np.prod(arr))     # Product of all elements => 1*2*3*4*5
print(np.min(arr))      # Minimum value in the array
print(np.max(arr))      # Maximum value in the array
print(np.mean(arr))     # Mean (average) of the elements
print(np.std(arr))      # Standard deviation (spread of data)
print(np.var(arr))      # Variance (square of standard deviation)
print(np.median(arr))   # Median (middle value after sorting)
print(np.argmin(arr))   # Index of the minimum value
print(np.argmax(arr))   # Index of the maximum value

15
120
1
5
3.0
1.4142135623730951
2.0
3.0
0
4


In [3]:
#power function
arr1=np.array([1,2,3,4,5])

print(np.square(arr1))   # Squares each element => x^2
print(np.sqrt(arr1))     # Square root of each element => √x
print(np.pow(arr1, 3))   # Raises each element to the power of 3 => x^3


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [4]:
#Log and Exponential Function
arr2=np.array([1,2,3,4,5])

print(np.log(arr2))     # Natural logarithm (base e) of each element
print(np.log10(arr2))   # Logarithm base 10 of each element
print(np.log2(arr2))    # Logarithm base 2 of each element
print(np.exp(arr2))     # Exponential function => e^x for each element

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [5]:
#Rounding Function => These functions are used to control decimal values.

print(np.round(3.14))   # Rounds to nearest integer (default 0 decimal places)
print(np.ceil(3.14))    # Rounds UP to the next integer (ceiling value)
print(np.floor(3.14))   # Rounds DOWN to the previous integer (floor value)
print(np.trunc(3.14))   # Removes decimal part (truncates toward zero)

3.0
4.0
3.0
3.0


In [6]:
#Some Extra Function
arr3=np.array([1,2,8,3,4,5,2,3,4])
print(np.unique(arr3))   # Returns unique (distinct) elements in sorted order
print(np.sort(arr3))     # Returns the array sorted in ascending order

arr4=np.array([1,2,-8,3,-4,5,2,-3,4,-9])

print(np.abs(arr4))      ## Returns absolute values (converts negatives to positive)


[1 2 3 4 5 8]
[1 2 2 3 3 4 4 5 8]
[1 2 8 3 4 5 2 3 4 9]
