#  NumPy 2D & 3D Array Operations
 - Sum
 - Indexing
 - Slicing
 - Manipulation

In [1]:
import numpy as np

In [2]:
#Multidimensional array

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print("Sum of all the elements in array =",np.sum(arr2D),"\n")

#Sum Operation using columns wise
sum_of_column=np.sum(arr2D,axis =0)
print("Sum of Columns are =",sum_of_column)

#Sum Operation using rows wise
sum_of_rows=np.sum(arr2D, axis=1)
print("Sum of Rows are =",sum_of_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all the elements in array = 45 

Sum of Columns are = [12 15 18]
Sum of Rows are = [ 6 15 24]


In [3]:
# 1 2 3
# 4 5 6
# 7 8 9 access 2 and 5

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2 , 1:2])

[[2]
 [5]]


In [4]:
#3D array (2 layers × 3 rows × 2 columns)
arr3D = np.array([
    [[1,2],[3,4],[5,6]],
    [[7,8],[9,10],[11,12]]
]) 

print(arr3D, arr3D.shape)

#indexing/accessing
print(arr3D[0,1,1])  # element from 1st layer, 2nd row, 2nd column
print(arr3D[1,0,1] ,"\n") # element from 2nd layer, 1st row, 2nd column

#slicing
print(arr3D[:,0,:],"\n") #first row from both layer
print(arr3D[:,1,:],"\n") #second row from both layer

print(arr3D[:,:,1],"\n") #second columns from both layer

#Manipulating 
arr3D[:,0,:]=99 #sets all elements of first rows across every layer in the 3D array to 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
8 

[[1 2]
 [7 8]] 

[[ 3  4]
 [ 9 10]] 

[[ 2  4  6]
 [ 8 10 12]] 

[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]
