# Numpy array creation using List and from Scratch
 - create from list
 - create numpy array from scratch

In [1]:
import numpy as np

In [2]:
#create - from lists
arr = np.array([12,3,4,5,6])
print(arr,type(arr))

arr2 = np.array([12,3,4,5,6,"prime"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)



[12  3  4  5  6] <class 'numpy.ndarray'>
['12' '3' '4' '5' '6' 'prime'] <class 'numpy.ndarray'> <U21 (6,)


In [3]:
arr2D = np.array([[1,2,3], [4,5,6] , [7,8,9]])
print(arr2D, arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [4]:
# -------------------------------
# Create NumPy arrays from scratch
# -------------------------------

In [5]:
arr1 = np.zeros((2,3), dtype = "int64") #prefill with zero values
print("Array1 (Zeros Array):","\n", arr1, arr1.shape,"\n")

arr3 = np.ones((2,3)) #prefill with one values
print("Array3 (Ones Array):","\n", arr3, arr3.shape, "\n")

#create one dimensional array
arr4 = np.ones((2,))
print("Array4(1D Ones Array):","\n",arr4, arr4.shape,"\n")

arr5 = np.full((3,4),100) #prefill with val
print("Array5 (Constant Value Array):","\n",arr5, arr5.shape,"\n")

arr6 = np.eye(3) #create identity matrix
print("Array6 (Identity Matrix):","\n",arr6, arr6.shape,"\n")

arr7 = np.arange(3,10,2)  #range elements
print("Array7 (Range Array):","\n",arr7, arr7.shape,"\n")

arr8 = np.linspace(1,100,4)  #evenly spaced arrays
print("Array8 (Linearly Spaced Array):","\n",arr8, arr8.shape,"\n")



Array1 (Zeros Array): 
 [[0 0 0]
 [0 0 0]] (2, 3) 

Array3 (Ones Array): 
 [[1. 1. 1.]
 [1. 1. 1.]] (2, 3) 

Array4(1D Ones Array): 
 [1. 1.] (2,) 

Array5 (Constant Value Array): 
 [[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4) 

Array6 (Identity Matrix): 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3) 

Array7 (Range Array): 
 [3 5 7 9] (4,) 

Array8 (Linearly Spaced Array): 
 [  1.  34.  67. 100.] (4,) 

