# Vectorization, Broadcasting, and Normalization in NumPy

In [1]:
import numpy as np

In [2]:
#Vectorization =>performing operations on entire arrays at once instead of using Python loops.

arr=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr**2)
print(arr+10)
print(arr + arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [3]:
# Broadcasting =>When operating on two arrays, NumPy compares their shapes element-wise. 
# It starts with the trailing (i.e. rightmost) dimension and works its way left. 
# Two dimensions are compatible when
# - they are equal, or
# - one of them is 1.

arr3=np.array([1,2,3,4,5])  #(5, ) =>(1,5) {1rows,5columns}
arr4= np.array([[1,2,3,4,5],[1,2,3,4,5]]) #(2,5)
print(arr3.shape)
print(arr4.shape)
print(arr3+arr4)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [4]:
#Normalization => Transforming its values. So they fit into a specific scale or range.
# This uses Z-score normalization: (value - mean) / standard deviation

arr5=np.array([
    [1,2],
    [3,4]])           # Create a 2D NumPy array

mean=np.mean(arr5)
std_dev=np.std(arr5)

print("Mean:",mean)
print("Standard Deviation:",std_dev)

# Each element is shifted by the mean and scaled by the standard deviation
normalized_arr =(arr-mean)/std_dev
print("Normalized Array:\n", normalized_arr)

Mean: 2.5
Standard Deviation: 1.118033988749895
Normalized Array:
 [-1.34164079 -0.4472136   0.4472136   1.34164079  2.23606798]
