# NumPy Array Properties and Data Type Conversion
 - shape
 - size
 - datatype
 - ndim
 - and convert the type int to float


In [1]:
import numpy as np

In [2]:
#Array Properties

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape) # to check dimension (rows × columns)
print(arr.size) # total elements - 9
print(arr.dtype) # data type of elements in the array
print(arr.ndim) # total number of dimension (2 for a 2D array)
print("\n") # for new line

#to convert the type int into float
float_array = arr.astype(np.float64)
print(float_array,float_array.dtype)

(3, 3)
9
int64
2


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64
