# Single Neuron Using PyTorch

In [1]:
import torch
import torch.nn as nn

### Step 1: Create Input 

In [2]:
torch.manual_seed(42)  #generate same random number after each run
inputs = torch.tensor([1.0, 2.0, 3.0])

### Step 2: Create a Single Neuron

Create one linear neuron with:
- Input Features = 3
- Output Features = 1

In [3]:
neuron = nn.Linear(in_features=3, out_features=1)

### Step 3: Pass the input through the neuron to calculate the output.

In [4]:
output = neuron(inputs)

In [5]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

### Step 4: View the Weights

In [6]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

### Step 5: View the Bias

In [7]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

### Step 6: Verify the Linear Equation
 - y=Wx+b

In [8]:
# verify using .. Formula
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)